export const userActionTypes = {
  LOGIN_USER: "LOGIN_USER",
  LOGOUT_USER: "LOGOUT_USER",
  SET_USER_DATA: "SET_USER_DATA",
  CLEAR_USER_DATA: "CLEAR_USER_DATA",
  SET_USER_AUTHENTICATED: "SET_USER_AUTHENTICATED",
  SET_USER_UNAUTHENTICATED: "SET_USER_UNAUTHENTICATED",
  SET_NOTIFICATION_DATA: "SET_NOTIFICATION_DATA",
  MARK_NOTIFICATIONS_READ: "MARK_NOTIFICATIONS_DATA",
  SET_USER_UPVOTES: "SET_USER_UPVOTES",
  SET_USER_DOWNVOTES: "SET_USER_DOWNVOTES",
  UPVOTE_POST: "UPVOTE_POST",
  DOWNVOTE_POST: "DOWNVOTE_POST",
  START_LOADING: "SET_LOADING",
  STOP_LOADING: "STOP_LOADING"
};

export const feedActionTypes = {
  LOAD_PUBLIC_FEED: "LOAD_PUBLIC_FEED",
  LOAD_PRIVATE_FEED: "LOAD_PRIVATE_FEED",
  SET_FEED: "SET_FEED",
  SET_TRENDING_POSTS: "SET_TRENDING_POSTS",
  CLEAR_FEED: "CLEAR_FEED"
};
